[package]
authors = ["Saverio Miroddi <saverio.pub2@gmail.com>"]
edition = "2018"
name = "ray_tracer_challenge-progress"
version = "0.1.0"

[dev-dependencies]

demonstrate = "0.4.5"

[dependencies]

assert_float_eq = "1.1.3"
