[package]

authors = ["Saverio Miroddi <saverio.pub2@gmail.com>"]
edition = "2018"
name = "library"
version = "0.1.0"

[dev-dependencies]

demonstrate = "0.4.5"
indoc = "1.0.3"

[dependencies]

assert_float_eq = "1.1.3"
lazy_static = "1.4.0"
macros = {path = "../macros"}
rayon = "1.5.0"
sdl2 = "0.34.3"
smart-default = "0.6.0"
