[package]
authors = ["Saverio Miroddi <saverio.pub2@gmail.com>"]
edition = "2018"
name = "headless_astronaut_rendering"
version = "0.1.0"

[workspace]

[dependencies]

library = {path = "../library"}
